,a.base_date_str AS base_date_str /* 근태기준일 */
,a.user_id AS user_id /* 직원ID */
,a.start_work_date AS start_work_date /* 최초출근시간 */
,a.out_work_date AS out_work_date /* 최초퇴근시간 */
,a.final_start_work_date AS final_start_work_date /* 최종출근시간 */
,a.final_out_work_date AS final_out_work_date /* 최종퇴근시간 */
,a.start_work_ip AS start_work_ip /* 출근IP */
,a.out_work_ip AS out_work_ip /* 퇴근IP */
,a.outside_work_yn AS outside_work_yn /* 외근여부 */
,a.work_status_code AS work_status_code /* 근무상태 */
,a.vacation_kind_code AS vacation_kind_code /* 휴가종류 */
,a.etc_description AS etc_description /* 기타설명 */
,a.mod_yn AS mod_yn /* 수정여부 */
,a.tardy_yn AS tardy_yn /* 지각여부 */
,a.worked_time_value AS worked_time_value /* 근무시간 */
,a.reg_date AS reg_date /* 등록일 */
,a.mod_date AS mod_date /* 수정일 */
,a.reg_user_id AS reg_user_id /* 등록자ID */
,a.mod_user_id AS mod_user_id /* 수정자ID */