/* 포탈 팀원인 경우 : 금일 출근 정보 (17p) */
SELECT 
    OCD.*
FROM OFFICE6.OFFICE_COMMUTE_DAY OCD
WHERE OCD.BASE_DATE_STR = '20221004'
AND OCD.USER_ID = 'yamdeng';

/* 포탈 팀원인 경우 : 현재 휴가 정보 (17p) */
SELECT 
    OVU.*
FROM OFFICE6.OFFICE_VACATION_USER OVU
WHERE OVU.USER_ID = 'yamdeng';

/* 포탈 팀원인 경우 : 출/퇴근 (17p) */
UPDATE OFFICE6.OFFICE_COMMUTE_DAY
SET START_WORK_DATE = #{startWorkDate}, START_WORK_IP = #{loginIp}, WORK_STATE_CODE = {workStateCode}
WHERE BASE_DATE_STR = '20221003' AND USER_ID = 'yamdeng';

UPDATE OFFICE6.OFFICE_COMMUTE_DAY
SET OUT_WORK_DATE = #{outWorkDate}, START_WORK_IP = #{loginIp}, WORK_STATE_CODE = {workStateCode}
WHERE BASE_DATE_STR = '20221003' AND USER_ID = 'yamdeng'

/* 포탈 팀원인 경우 : 팀원 근무 현황 (17p) */
SELECT 
    OCD.*
FROM OFFICE6.OFFICE_COMMUTE_DAY OCD
     INNER JOIN OFFICE6.USER USER
                OCD.USER_ID = USER.ID
     INNER JOIN OFFICE6.DEPT DEPT
             ON USER.DEPT_ID = DEPT.ID
WHERE OCD.BASE_DATE_STR = '20221004'
AND USER.DEPT_ID = 'yamdeng-dept';

/* 포탈 팀장인 경우 : 팀원 근무/출퇴근 현황 (27p) */
SELECT 
    OCD.*
FROM OFFICE6.OFFICE_COMMUTE_DAY OCD
     INNER JOIN OFFICE6.USER USER
                OCD.USER_ID = USER.ID
     INNER JOIN OFFICE6.DEPT DEPT
             ON USER.DEPT_ID = DEPT.ID
WHERE OCD.BASE_DATE_STR = '20221004'
AND USER.DEPT_ID = 'yamdeng-dept';

/* 포탈 팀장인 경우 : 업무 보고 현황 (27p) */
SELECT *
FROM OFFICE6.TEAM_REPORT TR
WHERE TR.DEPT_ID = 'yamdeng-dept'
AND TR.REPORT_DATE_STR >= '오늘날짜' AND TR.REPORT_DATE_STR < 오늘날짜 - 7일

/* 포탈 실장인 경우 : 실원 근무/출퇴근 현황 (28P) */
SELECT 
    OCD.*
FROM OFFICE6.OFFICE_COMMUTE_DAY OCD
     INNER JOIN OFFICE6.USER USER
                OCD.USER_ID = USER.ID
     INNER JOIN OFFICE6.DEPT DEPT
             ON USER.DEPT_ID = DEPT.ID
WHERE OCD.BASE_DATE_STR = '20221004'
AND USER.DEPT_ID IN ('yamdeng-dept', 'yamdeng-dept2');


/* 포탈 실장인 경우 : 팀 업무 보고 현황 (28P) */
SELECT *
FROM OFFICE6.TEAM_REPORT TR
     INNER JOIN OFFICE6.DEPT DEPT
             ON TR.DEPT_ID = DEPT.ID
WHERE TR.DEPT_ID IN ('yamdeng-dept', 'yamdeng-dept2')
AND TR.REPORT_DATE_STR >= '오늘날짜' AND TR.REPORT_DATE_STR < 오늘날짜 - 7일;


/* 포탈 실장인 경우 : 실원 근무/출퇴근 현황(summary 정보) (29P) */
SELECT 
    OCD.*
FROM OFFICE6.OFFICE_COMMUTE_DAY OCD
     INNER JOIN OFFICE6.USER USER
                OCD.USER_ID = USER.ID
     INNER JOIN OFFICE6.DEPT DEPT
             ON USER.DEPT_ID = DEPT.ID
WHERE OCD.BASE_DATE_STR = '20221004'
AND USER.DEPT_ID IN ('yamdeng-dept', 'yamdeng-dept2');

SELECT *
FROM OFFICE6.TEAM_REPORT TR
     INNER JOIN OFFICE6.DEPT DEPT
             ON TR.DEPT_ID = DEPT.ID
WHERE TR.DEPT_ID IN ('yamdeng-dept', 'yamdeng-dept2')
AND TR.REPORT_DATE_STR >= '오늘날짜' AND TR.REPORT_DATE_STR < 오늘날짜 - 7일;

-- 실장에 속한 하위 사용자 명수
SELECT COUNT(*)
FROM OFFICE6.USER USER
WHERE USER.DEPT_ID IN ('yamdeng-dept', 'yamdeng-dept2')
AND USE_YN = 'Y';


/* 포탈 관리자인 경우 : 전체 summary 정보 (30P) */
SELECT SUMMARY_KIND AS 'DEPT', COUNT(*)
FROM OFFICE6.DEPT
WHERE USE_YN = 'Y'
UNION
-- 전체인원 수
SELECT SUMMARY_KIND AS 'USER', COUNT(*)
FROM OFFICE6.USER
WHERE USE_YN = 'Y'
UNION
-- 휴가/휴직 인원
SELECT 
    SUMMARY_KIND AS 'VACATION', COUNT(*)
FROM OFFICE6.OFFICE_COMMUTE_DAY OCD
WHERE OCD.BASE_DATE_STR = '20221004'
AND VACATION_CODE IS NOT NULL
UNION
-- 지각
SELECT 
    SUMMARY_KIND AS 'COMMUTE_DEPT', COUNT(*)
FROM OFFICE6.OFFICE_COMMUTE_DEPT_DAY OCDD
WHERE OCDD.SUBMIT_DATE_STR = '20221004'
AND SUBMIT_STATE_CODE = '지각'
UNION
-- 출퇴근 미제출
SELECT 
    SUMMARY_KIND AS 'COMMUTE_DEPT', COUNT(*)
FROM OFFICE6.OFFICE_COMMUTE_DEPT_DAY OCDD
WHERE OCDD.SUBMIT_DATE_STR = '20221004'
AND SUBMIT_STATE_CODE IS NULL
UNION
-- 업무보고 이슈여부
SELECT SUMMARY_KIND AS 'REPORT_ISSUE', COUNT(*)
FROM OFFICE6.TEAM_REPORT TR
WHERE TR.REPORT_DATE_STR = '20221004'
AND ISSUE_YN = 'Y'
UNION
-- 업무보고 미제출
SELECT SUMMARY_KIND AS 'REPORT_NOT_SUBMIT', COUNT(*)
FROM OFFICE6.TEAM_REPORT TR
WHERE TR.REPORT_DATE_STR = '20221004'
AND TR.REPORT_STATE IS NULL
UNION
-- 업무보고 등록
SELECT SUMMARY_KIND AS 'REPORT_COMPLETE', COUNT(*)
FROM OFFICE6.TEAM_REPORT TR
WHERE TR.REPORT_DATE_STR = '20221004'
AND TR.REPORT_STATE = '정상제출'

-- 출퇴근 전체
SELECT SUBMIT_STATE_CODE, COUNT(*)
FROM OFFICE6.OFFICE_COMMUTE_DEPT_DAY OCDD
WHERE OCDD.SUBMIT_DATE_STR = '20221004'
GROUP BY SUBMIT_STATE_CODE

-- 업무보고 전체
SELECT REPORT_STATE, COUNT(*)
FROM OFFICE6.TEAM_REPORT TR
WHERE TR.REPORT_DATE_STR = '20221004'
GROUP BY REPORT_STATE





