INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220101', '신정', 'SAT', 'WEEKEND');

INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220131', '설날연휴', 'MON', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220201', '설날연휴', 'TUE', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220202', '설날연휴', 'WED', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220301', '삼일절', 'TUE', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220309', '대통령선거', 'WED', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220505', '어린이날', 'THU', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220601', '전국동시지방선거', 'WED', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220606', '현충일', 'MON', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220815', '광복절', 'MON', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220910', '추석연휴', 'SAT', 'WEEKEND');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220911', '추석연휴', 'SUN', 'WEEKEND');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20220912', '추석연휴', 'MON', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20221003', '개천절', 'MON', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20221009', '한글날', 'SUN', 'WEEKEND');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20221010', '한글날(대체휴일)', 'MON', 'WEEKDAY');
INSERT INTO OFFICE_WORK_HOLIDAY(BASE_YEAR, HOLI_DATE_STR, NAME, WEEKDAY_CODE, WEEKEND_CODE)
VALUES('2022', '20221225', '크리스마스', 'SUN', 'WEEKEND');